use_frameworks!

platform :ios, '9.0'

target 'DZMacroAndCategoryModule_Example' do
  pod 'DZMacroAndCategoryModule', :path => '../'

  target 'DZMacroAndCategoryModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
